default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: [
            "-c",
            "--skip-glob protobuf"
        ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8
  - repo: local
    hooks:
    - id: poetry
      name: poetry check
      entry: poetry check
      pass_filenames: false
      language: system
      files: ^pyproject\.toml$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [
            "--sqlite-cache"
        ]
