name: Linters

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy isort
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Run isort
        run: isort -c .